# Jekyll Resume Theme

# Site settings
title: Manuel Jiménez 
email: manuel@jimenez.eu.org
description: My résumé
baseurl: ""
url: "https://www.manueljimenez.eu.org"
name: Manuel Jiménez
job: data engineer
location: Bloomington, IN
languages: English, Spanish
github_username:  mjbfm99
email_address: manuel@jimenez.eu.org

# Build settings
markdown: kramdown
